title: TCCN Criminal Database
description: Official criminal records for the server
baseurl: "/TTTAR"
url: "https://microphonicwire-blip.github.io"

remote_theme: just-the-docs/just-the-docs@v0.10.0

color_scheme: dark

search_enabled: true
search:
  heading_level: 2
  previews: 3

nav_sort: order

aux_links:
  "Discord":
    - "https://discord.gg/D5AJ44bsf2"

footer_content: "TCCN Criminal Database. For authorized members only."

plugins:
  - jekyll-seo-tag
footer_custom_content: "{% include groq_badge.html %}"
